In [1]:
import pandas as pd

In [8]:
df = pd.read_csv("articles_data.csv", index_col='index')

In [13]:
df

,source_id,source_name,author,title,description,url,url_to_image,published_at,content,top_article,engagement_reaction_count,engagement_comment_count,engagement_share_count,engagement_comment_plugin_count
index,,,,,,,,,,,,,,
0,reuters,Reuters,Reuters Editorial,NTSB says Autopilot engaged in 2018 California...,The National Transportation Safety Board said ...,https://www.reuters.com/article/us-tesla-crash...,https://s4.reutersmedia.net/resources/r/?m=02&...,2019-09-03T16:22:20Z,WASHINGTON (Reuters) - The National Transporta...,0.0,0.0,0.0,2528.0,0.0
1,the-irish-times,The Irish Times,Eoin Burke-Kennedy,Unemployment falls to post-crash low of 5.2%,Latest monthly figures reflect continued growt...,https://www.irishtimes.com/business/economy/un...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-03T10:32:28Z,The States jobless rate fell to 5.2 per cent l...,0.0,6.0,10.0,2.0,0.0
2,the-irish-times,The Irish Times,Deirdre McQuillan,"Louise Kennedy AW2019: Long coats, sparkling t...",Autumn-winter collection features designerâ€™s g...,https://www.irishtimes.com/\t\t\t\t\t\t\t/life...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-03T14:40:00Z,Louise Kennedy is showing off her autumn-winte...,1.0,NaN,NaN,NaN,NaN
3,al-jazeera-english,Al Jazeera English,Al Jazeera,North Korean footballer Han joins Italian gian...,Han is the first North Korean player in the Se...,https://www.aljazeera.com/news/2019/09/north-k...,https://www.aljazeera.com/mritems/Images/2019/...,2019-09-03T17:25:39Z,"Han Kwang Song, the first North Korean footbal...",0.0,0.0,0.0,7.0,0.0
4,bbc-news,BBC News,BBC News,UK government lawyer says proroguing parliamen...,"The UK government's lawyer, David Johnston arg...",https://www.bbc.co.uk/news/av/uk-scotland-4956...,https://ichef.bbci.co.uk/news/1024/branded_new...,2019-09-03T14:39:21Z,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10432,abc-news,ABC News,The Associated Press,Drop in US service sector activity raises econ...,"Get breaking national and world news, broadcas...",https://abcnews.go.com/Business/wireStory/drop...,https://s.abcnews.com/images/US/WireAP_eb147c9...,2019-10-03T16:30:16Z,Growth in the U.S. economys vast services sect...,0.0,0.0,0.0,0.0,0.0
10433,reuters,Reuters,Sumeet Chatterjee,Banker defections pose challenge for Credit Su...,The announcement by Julius Baer this week that...,https://www.reuters.com/article/us-credit-suis...,https://s3.reutersmedia.net/resources/r/?m=02&...,2019-10-03T15:59:52Z,ZURICH/HONG KONG (Reuters) - The announcement ...,0.0,0.0,0.0,627.0,0.0
10434,cnn,CNN,"Lauren M. Johnson, CNN","A 5-year-old cancer survivor donates 3,000 toy...",Weston Newswanger is just a normal 5-year-old ...,https://www.cnn.com/2019/10/03/us/five-year-ol...,https://cdn.cnn.com/cnnnext/dam/assets/1910021...,2019-10-03T11:20:06Z,NaN,0.0,4072.0,179.0,466.0,0.0
10435,cbs-news,CBS News,CBS News,Fateful Connection,A detective is haunted by the case of two wome...,https://www.cbsnews.com/video/fateful-connecti...,https://cbsnews1.cbsistatic.com/hub/i/r/2019/1...,2019-10-03T16:40:03Z,NaN,0.0,0.0,0.0,0.0,0.0
10436,cbs-news,CBS News,CBS News,"Love, Hate & Obsession",Who wanted one-time millionaire Lanny Horwitz ...,https://www.cbsnews.com/video/love-hate-obsess...,https://cbsnews1.cbsistatic.com/hub/i/r/2017/0...,2019-10-03T16:35:13Z,NaN,0.0,0.0,0.0,0.0,0.0

In [35]:
df['reactions_count'] = df['engagement_reaction_count'] + df['engagement_comment_count'] + df['engagement_share_count']

In [33]:
df.sort_values(by = ['reactions_count'], ascending = False).iloc[0:5]

,source_id,source_name,author,title,description,url,url_to_image,published_at,content,top_article,engagement_reaction_count,engagement_comment_count,engagement_share_count,engagement_comment_plugin_count,reactions_count
index,,,,,,,,,,,,,,,
8500,cnn,CNN,Elizabeth Wolfe And Brian Ries,"Jimmy Carter, the oldest living former U.S. pr...","Jimmy Carter, the oldest living former U.S. pr...",https://www.cnn.com/2019/10/01/us/jimmy-carter...,https://cdn.cnn.com/cnnnext/dam/assets/1909241...,2019-10-01T10:40:23Z,NaN,0.0,354132.0,41293.0,39422.0,8.0,434847.0
2075,bbc-news,BBC News,BBC News,Zimbabwe ex-President Robert Mugabe dies aged 95,"Robert Mugabe, Zimbabwe's first post-independe...",http://www.bbc.co.uk/news/world-africa-49604152,https://ichef.bbci.co.uk/news/1024/branded_new...,2019-09-06T05:04:07Z,"Robert Mugabe, Zimbabwe's first post-independe...",1.0,125106.0,48490.0,32921.0,0.0,206517.0
8834,abc-news,ABC News,Bill Hutchinson,Amber Guyger convicted of murder in wrong-apar...,Amber Guyger convicted of murder in wrong-apar...,https://abcnews.go.com/US/amber-guyger-convict...,https://s.abcnews.com/images/US/guyger-1-ap-er...,2019-10-01T15:48:31Z,A Texas jury rejected former Dallas police off...,0.0,91311.0,20128.0,22080.0,0.0,133519.0
5092,the-new-york-times,The New York Times,Coral Davenport,Trump Administration to Finalize Rollback of C...,The administration is expected to complete the...,https://www.nytimes.com/2019/09/12/climate/tru...,https://static01.nyt.com/images/2018/12/11/cli...,2019-09-12T13:19:36Z,"The repeal of the water rule, which is schedul...",0.0,66910.0,15234.0,24519.0,0.0,106663.0
225,bbc-news,BBC News,https://www.facebook.com/bbcnews,Brexit: Tory MP defects ahead of crucial no de...,Phillip Lee's move leaves Boris Johnson with n...,https://www.bbc.co.uk/news/uk-politics-49570682,https://ichef.bbci.co.uk/news/1024/branded_new...,2019-09-03T14:48:14Z,Conservative MP Philip Lee has defected to the...,0.0,60117.0,19043.0,10752.0,0.0,89912.0

In [34]:
df.sort_values(by = ['reactions_count'], ascending = True).iloc[0:5]

,source_id,source_name,author,title,description,url,url_to_image,published_at,content,top_article,engagement_reaction_count,engagement_comment_count,engagement_share_count,engagement_comment_plugin_count,reactions_count
index,,,,,,,,,,,,,,,
10436,cbs-news,CBS News,CBS News,"Love, Hate & Obsession",Who wanted one-time millionaire Lanny Horwitz ...,https://www.cbsnews.com/video/love-hate-obsess...,https://cbsnews1.cbsistatic.com/hub/i/r/2017/0...,2019-10-03T16:35:13Z,NaN,0.0,0.0,0.0,0.0,0.0,0.0
1825,al-jazeera-english,Al Jazeera English,Al Jazeera,Hong Kong police target protesters with rubber...,Pro-democracy protesters rally near subway sta...,http://www.aljazeera.com/news/2019/09/hong-kon...,https://www.aljazeera.com/mritems/Images/2019/...,2019-09-06T15:39:00Z,"Hong Kong police have fired rubber bullets, te...",1.0,0.0,0.0,0.0,0.0,0.0
5786,the-irish-times,The Irish Times,Elizabeth Birdthistle,Irish collectors secure strong prices for Brit...,"RESULTS Saturday, September 7th Woodward Aucti...",https://www.irishtimes.com/life-and-style/home...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-14T05:00:00Z,"RESULTS\r\nSaturday, September 7th\r\nWoodward...",0.0,0.0,0.0,0.0,0.0,0.0
1828,cbs-news,CBS News,CBS News,CBSN Originals - Terror in Brussels,CBSN's Vladimir Duthiers investigates the neig...,https://www.cbsnews.com/video/cbsn-originals-t...,https://cbsnews3.cbsistatic.com/hub/i/r/2019/0...,2019-09-06T17:07:03+00:00,CBSN's Vladimir Duthiers investigates the neig...,1.0,0.0,0.0,0.0,0.0,0.0
1829,the-irish-times,The Irish Times,CiarÃ¡n Hancock,Spirit level: Teeling Whiskey aims for the 1 m...,Teeling Whiskey increased its pre-tax profit l...,https://www.irishtimes.com/business/agribusine...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-06T15:49:22Z,Teeling Whiskey increased its pre-tax profit l...,0.0,0.0,0.0,0.0,0.0,0.0